permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 微尘

title: 微尘 

url: http://azeril.me  
description: Love me less，but love me for a long.——The Lover's Dictionary

# gavatar头像及Favicon
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: http://dreamofbook.qiniudn.com/favicon.png

author: 
  name: Azeril
  email: azeril@live.cn
  github: Azeril
  douban: Azeril
  Goodreads: Azeril
  twitter: Azeril_Lapland
  pinterest: Azeril_Lapland
  bio: 明朝即長路 惜取此時心
  email_md5: 7a3f53fc97562e5a42cffc4d8e0f3bbc

BASE_PATH:
