permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 微尘

description: Love me less，but love me for a long.——The Lover's Dictionary
# gavatar头像及Favicon
gavatar: http://pic.yupoo.com/azeril/Ef3mi84v/medish.jpg
favicon: http://pic.yupoo.com/azeril/Ef3mi84v/medish.jpg

author:
  name: Azeril
  email: azeril@live.cn
  github: Azeril
  twitter: Azeril_Lapland
  pinterest: Azeril
  Douban: Azeril 
  bio: 明朝即長路 惜取此時心
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
